//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMMAConversions.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_TMMA_PRODUCTS
    {
        public int ProductsID { get; set; }
        public Nullable<int> BOMFileID { get; set; }
        public Nullable<int> RoutingFileID { get; set; }
        public int ProductsTypeID { get; set; }
        public Nullable<decimal> Version { get; set; }
        public int IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
