//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMMAConversions.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_TMMA_MASTER_MESSAGE
    {
        public int MessageID { get; set; }
        public string MessageText { get; set; }
        public string TypeOfMessage { get; set; }
        public string MessageClass { get; set; }
        public string MassageNumber { get; set; }
        public string MessageGroup { get; set; }
        public string MessageLevel { get; set; }
        public int IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
